In [1]:
%pylab inline
%load_ext autoreload
%autoreload 2

Populating the interactive namespace from numpy and matplotlib

In [2]:
import self_plan.finance.api as fa

In [9]:
fa.get_current_net_asset

'E:\\04_project'

In [7]:
datelist = ('2018-01-01', '2018-02-01', '2018-03-01','2018-04-01')

# 读取指定日期净资产总额

In [12]:
# 给定起始和结束日期 默认为读取所有日期 
fa.get_net_asset_amount('2018-01-01', '2018-05-04')

[INFO] 2018-03-30 20:09:18 E:\01_learn\05_method\finance.db is connected.
[INFO] 2018-03-30 20:09:18 SELECT * FROM net_asset_amount WHERE date >= '2018-01-01'and date <= '2018-05-04'
[INFO] 2018-03-30 20:09:18 E:\01_learn\05_method\finance.db is disconnected.

         date  net_asset
0  2018-01-01  540624.00
1  2018-02-01  551367.00
2  2018-03-01  587982.00
3  2018-04-01  629240.94

# 读取指定日期净资产结构

In [13]:
# 读取给定时间间隔之间的所有净资产结构记录  默认为读取最新日期
fa.get_net_asset_structure()

[INFO] 2018-03-30 20:09:25 E:\01_learn\05_method\finance.db is connected.
[INFO] 2018-03-30 20:09:25 SELECT * FROM net_asset_structure WHERE date = (SELECT max(date) FROM net_asset_structure)
[INFO] 2018-03-30 20:09:25 E:\01_learn\05_method\finance.db is disconnected.

         date subclass  current_value
8  2018-04-01       负债      -24433.00
7  2018-04-01       股票       13792.00
5  2018-04-01    指数型基金       19968.00
1  2018-04-01    债券型基金       20072.00
2  2018-04-01    偏股型基金       25794.00
0  2018-04-01      P2P       92874.00
6  2018-04-01       现金      111926.94
4  2018-04-01       定期      369247.00
3  2018-04-01      净资产      629240.94

# 读取指定日期的资产结构及配置合理度

In [16]:
# 读取给定时间间隔之间的所有资产结构及配置记录  默认为读取最新日期
fa.get_asset_structure()

[INFO] 2018-03-30 20:19:45 E:\01_learn\05_method\finance.db is connected.
[INFO] 2018-03-30 20:19:45 SELECT * FROM asset_structure WHERE date = (SELECT max(date) FROM asset_structure)
[INFO] 2018-03-30 20:19:45 E:\01_learn\05_method\finance.db is disconnected.

,date,subclass,current_value,pct,planning_prop,planning_value,comments
7,2018-04-01,股票,13792.00,0.021099,0.025,16341.8485,2549.8485
5,2018-04-01,指数型基金,19968.00,0.030547,0.030,19610.2182,-357.781800000001
2,2018-04-01,债券型基金,20072.00,0.030706,0.055,35952.0667,15880.0667
3,2018-04-01,偏股型基金,25794.00,0.039460,0.030,19610.2182,-6183.7818
0,2018-04-01,P2P,92874.00,0.142080,0.050,32683.6970,-60190.303
6,2018-04-01,现金,111926.94,0.171227,0.010,6536.7394,-105390.2006
4,2018-04-01,定期,369247.00,0.564879,0.800,522939.1520,153692.152
1,2018-04-01,total,653673.94,1.000000,NaN,NaN,None

# 读取给定时间间隔之间的所有固收类资产流动性记录

In [17]:
# subclass是根据实时计算出的剩余到期日计算的
fa.get_fix_liq_info()

[INFO] 2018-03-30 20:20:59 E:\01_learn\05_method\finance.db is connected.
[INFO] 2018-03-30 20:20:59 SELECT * FROM fix_liq_info WHERE date = (SELECT max(date) FROM fix_liq_info)
[INFO] 2018-03-30 20:20:59 E:\01_learn\05_method\finance.db is disconnected.

,date,subclass,total_amount,pct,planning_prop,planning_value,comments
3,2018-04-01,超长期定期,70173.00,0.107114,0.05,18462.35,-51710.65
0,2018-04-01,中期定期,95330.00,0.145515,0.78,288012.66,192682.66
4,2018-04-01,长期定期,119239.00,0.182010,0.05,18462.35,-100776.65
2,2018-04-01,短期定期,139547.00,0.213009,0.10,36924.70,-102622.3
1,2018-04-01,现金,230832.92,0.352351,0.02,7384.94,-223447.98

# 读取给定时间间隔之间的所有固收类资产收益率记录

In [19]:
fa.get_fix_return_rate()

[INFO] 2018-03-30 20:24:37 E:\01_learn\05_method\finance.db is connected.
[INFO] 2018-03-30 20:24:37 SELECT * FROM fix_return_rate WHERE date = (SELECT max(date) FROM fix_return_rate)
[INFO] 2018-03-30 20:24:37 E:\01_learn\05_method\finance.db is disconnected.

          date category               item     ytm   ytm_avg weight
3   2018-04-01      P2P           U计划7058期  0.0920  0.059603  1.90%
1   2018-04-01      P2P           U计划0613期  0.0880  0.059603  0.76%
2   2018-04-01      P2P           U计划6013期  0.0880  0.059603  6.14%
4   2018-04-01      P2P           U计划8417期  0.0880  0.059603  3.93%
0   2018-04-01      P2P           U计划0521期  0.0810  0.059603  3.81%
9   2018-04-01       定期    光大永明定活宝20180717  0.0600  0.059603  6.91%
10  2018-04-01       定期    光大永明定活宝20180726  0.0600  0.059603  3.73%
6   2018-04-01       定期      京弘年年盈20170809  0.0580  0.059603  0.93%
7   2018-04-01       定期      京弘年年盈20170927  0.0580  0.059603  2.76%
14  2018-04-01       定期         厦金中心厦盈通第二期  0.0568  0.059603  1.88%
15  2018-04-01       定期         厦金中心厦盈通第八期  0.0568  0.059603  5.63%
21  2018-04-01       定期            平安享盈368  0.0560  0.059603  6.00%
11  2018-04-01       定期    光大永明定活宝20190108  0.0550  0.059603  2.85%
12  2018-04-01       定期    光大永明定活宝20190208  0.0550  0.059603  3.64%
13  2018-04-01       定期    光大永明定活宝20190226  0.0550  0.059603  3.64%
24  2018-04-01       定期            理享HK730  0.0550  0.059603  1.94%
25  2018-04-01       定期            理享HK731  0.0550  0.059603  1.36%
5   2018-04-01       定期      京弘年年盈20170620  0.0540  0.059603  3.73%
22  2018-04-01       定期     泰康养老瑞泰20171219  0.0540  0.059603  1.82%
26  2018-04-01       定期     财通财慧道安盈系列0925期  0.0530  0.059603  9.45%
8   2018-04-01       定期    光大永明定活宝20180514  0.0510  0.059603  1.50%
16  2018-04-01       定期         天金所支信通第33期  0.0510  0.059603  0.94%
17  2018-04-01       定期         天金所支信通第35期  0.0510  0.059603  2.83%
20  2018-04-01       定期   太平养老乐享太平20180817  0.0504  0.059603  1.83%
18  2018-04-01       定期   太平养老乐享太平20180320  0.0502  0.059603  9.50%
19  2018-04-01       定期  太平养老乐享太平20180320卖  0.0502  0.059603  9.59%
23  2018-04-01       定期            理享CS365  0.0500  0.059603  0.97%

# 读取给定时间间隔之间的所有权益类资产的收益记录

In [20]:
fa.get_equity_return_records()

[INFO] 2018-03-30 20:24:52 E:\01_learn\05_method\finance.db is connected.
[INFO] 2018-03-30 20:24:52 SELECT * FROM equity_return_records WHERE date = (SELECT max(date) FROM equity_return_records)
[INFO] 2018-03-30 20:24:52 E:\01_learn\05_method\finance.db is disconnected.

,item,status,hold_days,buy_cost,current_value,return,return_rate,date
0,华泰证券,持仓中,22 days 00:00:00,13615.27,13792.0,176.73,1.30%,2018-04-01
1,大摩强收益债券,持仓中,29 days 00:00:00,20000.00,20072.0,72.00,0.36%,2018-04-01
2,广发沪深300ETF002987,持仓中,98 days 00:00:00,20900.00,19968.0,-932.00,-4.46%,2018-04-01
3,银华估值005250,持仓中,110 days 00:00:00,26970.00,25794.0,-1176.00,-4.36%,2018-04-01
4,上海医药,落袋为安,60 days 00:00:00,9726.40,NaN,445.60,4.58%,2018-04-01
6,华域汽车,落袋为安,65 days 00:00:00,13032.00,NaN,464.21,3.56%,2018-04-01
5,康缘医药,落袋为安,60 days 00:00:00,1526.00,NaN,-120.00,-7.86%,2018-04-01

# 读取给定时间间隔之间的所有收益与消费记录